// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:radio_app/data/models/country_hive_model.dart';
import 'package:radio_app/data/models/genre_hive_model.dart';
import 'package:radio_app/data/models/station_hive_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CountryHiveModelAdapter());
    registerAdapter(GenreHiveModelAdapter());
    registerAdapter(StationHiveModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CountryHiveModelAdapter());
    registerAdapter(GenreHiveModelAdapter());
    registerAdapter(StationHiveModelAdapter());
  }
}
